name: Publish CI

on:
  push:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  publish:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@abc-widgets'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push
          git push --tags
      - run: yarn publish --access restricted
        env:
          # NOTE: using the built-in GITHUB token here because we're publishing to THIS repository's packages.
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}